config/routes.rb
Rails.application.routes.draw do

  resources :restaurants
  root "restaurants#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurant_controller.rb
class RestaurantController<ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_index_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :zip_code, :description, :category)

  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController<ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :zip_code, :description, :category)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurant/new.html.erb
<h1>Add a new restaurant</h1>


<p>Name, address, city, state, and zip code requried</p>


<%= form_for @restaurant, url: { action: "create" } do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :description   %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </p>
  <%= f.submit "Add restaurant" %>

<% end %>

<%= link_to "Home", restaurant_index_path %>

app/views/restaurants/index.html.erb
<h1>Good Eats</h1>

<% @restaurants.each do |r| %>
  <ul>
    <li>
      <%= link_to r.name, restaurant_path(r.id) %>
    </li>
  </ul>

<% end %>
<p>
<%= link_to "Add restaurant", new_restaurant_path %>
</p>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>
<p>Name, address, city, state, and zip code requried</p>

<%= form_for @restaurant, url: { action: "create" } do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :description   %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </p>
  <%= f.submit "Add restaurant" %>
<% end %>

<%= link_to "Home", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.category %></h2>

  <ul>
    <li>Address: <%= @restaurant.address %></li>
    <li>City: <%= @restaurant.city %></li>
    <li>State: <%= @restaurant.state %></li>
    <li>Zip: <%= @restaurant.zip_code %></li>
  </ul>

  <h4>Description:</h4>
<p>
  <%= @restaurant.description %>
</p>

<%= link_to "Home", restaurants_path %>
<%= link_to "Delete restaurant", [@restaurant], confirm: "Are you sure?", method: "delete" %>